#    ________      __          __   _  __
#   / ____/ /___  / /_  ____ _/ /  | |/ /
#  / / __/ / __ \\/ __ \\/ __ `/ /   |   /
# / /_/ / / /_/ / /_/ / /_/ / /   /   |
# \\____/_/\\____/_.___/\\__,_/_/   /_/|_|
#
# Main Config


HoverAndClickText:
  Enable: true
  Text: "&7&oClick to go!"
  Command: "/send %player% %target%"

GlobalChatPrefix:
  Enable: true
  Prefix: "!"

Groups:
  Owner:
    Prefix: "&4&lOWNER &4"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globachat.use.owner"
  Manager:
    Prefix: "&c&lMANAGER &c"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globachat.use.manager"
  SrAdmin:
    Prefix: "&c&lSRADMIN &c"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globachat.use.sradmin"
  Admin:
    Prefix: "&c&lADMIN &c"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globachat.use.admin"
  Youtuber:
    Prefix: "&c&lYOUTUBER &c"
    CoolDown: 10
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globachat.use.youtuber"
  Streamer:
    Prefix: "&5&lSTREAMER &5"
    CoolDown: 10
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globachat.use.streamer"